### ISSUE TITLE
Add ability to view layer attribute table

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-infomapper-ng#223]
Being able to show the attribute table for a layer would be useful.  See [this Watershed Resource Registry example](https://watershedresourcesregistry.org/map/?config=stateConfigs/southcarolina.json).  This website also illustrates a variation on using a "dot dot dot" menu for tools (rather than separate one-click icons), and it uses click-popup rather than mouse-over, with a menu to turn off popups.

**Comment by smalers** [comment]
I'm changing this to high priority.  Now that map features are in place to help with visualization and navigation, users are going to start digging into the data more.  Being able to view layer attributes in a table will be useful.  See issue #267, which proposes how to add a menu for tools.  If that is enabled, then viewing the attribute table could be implemented as a popup, for example using clusterize or a built-in Angular component.  Catherine uses a PrimeNG table but I'm not certain this is the best component, especially for large datasets.  Here are some considerations:

* TSTool has code to do table views of large datasets.  This uses an MVC design that works well, where data objects are retrieved for viewing as the user scrolls, rather than preloading all data into a viewer.  I can provide information.
* clusterize seems to be optimized for this approach.  One issue is does the attribute data from a GeoJSON layer need to be copied into a format for clusterize?  Or is there a way to integrate code MVC-style to access the original copy for the view?
* Advanced features would be to link the map and attribute table, for example select features on one and automatically select in the other.
* Users will likely want to filter on attributes.  This could a simple alphabetical sort on a selected column or a more complex filter to only show records that match the filter.  See Excel, QGIS, Esri, Colorado Information Marketplace tools for some examples.  This could be a separate issue involving a "Query Builder" for features.

**Comment by smalers** [comment]
Here are some thoughts on the design.  For TSTool/Java, there is a table model class that connects the business objects with the viewing component.    See the [DataTable_TableModel](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/Util/Table/DataTable_TableModel.java) Java class.  The UI component then calls the `getValueAt` method to retrieve data for display.  The other get methods provide number of columns, headings, widths, format, etc.  This is a nice MVC design because the UI code is separate from the data code.   The performance is also very good because only one copy of data is maintained (the original data list) and data for viewing is only retrieved as needed in order to populate a relatively small viewable area.  There is some sophistication in the scrolling because the UI needs to know the number of rows and columns to display.  The following are some points to consider:

* Need to handle all common data types and use string from "to string" as the default
* Need to handle missing values - typically null and NaN are shown as empty cells in the table
* Need to format date/time to appropriate precision - the Java code uses ISO 8601 formatting by default and the `DateTime` class includes precision so date/times are always formatted appropriately

**Comment by smalers** [comment]
I did a bit of research:

* [https://blog.angular-university.io/angular-material-data-table/][https://blog.angular-university.io/angular-material-data-table/]
* [DataTables with Angular](https://dzone.com/articles/learn-mvc-using-angular-datatable) - is "DataTables" a viable and useful library?
* [UIgrid](http://ui-grid.info/)
* [Angular grid](https://www.ag-grid.com/angular-grid/0)
* [3 ways to render large lists in Angular](https://blog.bitsrc.io/3-ways-to-render-large-lists-in-angular-9f4dcb9b65)

**Comment by smalers** [comment]
Here is my initial feedback on the initial implementation.

1. The general functionality is good.
2. The icon in the menu is OK; however, maybe use an icon that more clearly shows the header row so it looks like a table and not a grid.  We may add tools later that work on raster, in which case the current icon could be used.
3, The menu has a surrounding outline.  Can it be made to look like the main menu?  It would be nice to have consistent menu look and feel.
4. Change the menu to ***Data Table***, which is more understandable by the general users.
5. Centering in the column may be OK for now but using conventions consistent with other data tools may be better, as indicated below.
6. The general filter functionality is good.  It will need to be tested on a larger datasets.  Maybe change the hint that is shown to `Filter by substring in any column`.  The use of "keyword" does not make total sense since substrings are also supported, right?
7. Additional enhancements may be needed, based on use, such as the following, which can be added as separate issues, with varying priority:
    1. A checkbox column be added or otherwise allow a way to select rows?  This could be used to select for copy/paste and export, or interact with the map (such as highlight on table and then select/highlight corresponding features on map - this is a possible future feature but not a current priority).  See QGIS and other tools for typical behavior.  Adding such features does not impact performance.
    2. Change defaults to format columns based on type, for example to left-justify strings and right-justify numbers, and format floating point numbers with a precision.
    3. Add a copy/paste functionality.
    4. Add a ***Save*** button to save the full table (or selected rows, when selected functionality is added) to a file, such as CSV, and maybe Excel file.  In this case, the original map layer is not being saved, but the extracted attribute table.  If saving to CSV, it is appropriate to replace nulls and `NaN` with spaces.
    5. Maybe set the popup title to be something like the layer name and "Data Table".
    6. Perhaps need to optimize column width more.  What happens with really wide column data values, like a long sentence?  It can be difficult to optimize defaults so need to be careful with this.
    7. Can popups be resizable?   This might be particularly useful for the data table.

**Comment by smalers** [comment]
It seems like there is a need for more typescript code to manage the table viewing.  Here are some Java classes that may be useful.  It may be necessary to create at least similar skeleton classes in typescript to generically handle table displays.

* [DataTable](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/Util/Table/DataTable.java) - a generic object to hold tabular data, used when there is no business object for the data.  This is used, for example, when querying data from a database.  It could be used to hold data from a layer attribute table, but often there is other code to do this.
* [DataTable_TableModel](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/Util/Table/DataTable_TableModel.java) - maps between rows in DataTable to requests to view the row/column (cell value)
* [TableField](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/Util/Table/TableField.java) - stores metadata for a DataTable columns, useful because otherwise separate lists of metadata would be needed

**Comment by smalers** [comment]
I pulled the latest commit and looked at table behavior.  I realize that more needs to be done.  I observed the following issues:

1.  The attribute table scrolling appears to behave worse than before.  I did not push to the cloud due to this.  In particular, the table for counties and municipal boundaries from the Poudre Basin Information site do not scroll well, leaving rows blank when rows should be present.
2. The table cell values overflow for wide text, overwriting the next column.  This was seen in particular for URLs.  Need to make sure the displayed text fits in the column and either wrap, use "...", change the column width, etc.
3. It is possible to auto-format URLs to also be links, similar to click popups?
4. One thing that is interesting is why is the scroll bar overlapping the header in the first place?  Is there a way to locate the vertical scrollbar so that it only covers data rows and not the header?  TSTool and Java code does this and I think it solves a lot of scrolling issues.  This would maybe require too much internal code changing.
5. The table when scrolled to the bottom shows a few empty rows.  Why does this occur?  Is there integer/pixel math roundoff that is rounding display coordinates?

**Comment by smalers** [comment]
I pulled the latest commit.  It looks much better than the previous commit, especially the scrolling issues seem to have been resolved.  I have the following comments:

1. Can the title be put in the title bar area of the window to the left of the "x", rather than the body of the dialog?  Perhaps use a format similar to:  "Colorado Counties - Data Table".
2. The formatting of floating point numbers for number of digits is probably OK as default of 2 for now but there will be cases where that is not enough.  We'll have to figure out how to control that formatting, as well as for popups.  In particular, latitude and longitude should probably be 6 digits and some state water rights data uses 11.5 format as a number (but may be a string in attributes).  I'm a bit confused by behavior.  For example, for Poudre ***Basin Entities/Agriculture - Ditches*** the table for service areas shows WDID as number (right justified) but has leading zero.  An integer with leading zero often loses the leading the zero when read in.  I need to understand the behavior better to make sure there are no issues.
3. Long string fields don't allow automatically break lines in the table overflow cells.  This will require auto-sizing the column or some other approach.  One reason for showing the attribute table is to show full data, whereas the hover and click popups may need to truncate such data.
4. Some tables have extra whitespace on the right side even with scrollbar.  Is this a symptom of some other problem?
5. The row height could be made more compact.  Some rows have 2 lines of content and other rows with 1 line of content seem to be the same height.  Other rows have more lines of data.  The rows with one line seem to have extra vertical padding.  I'm looking at the Poudre ***Basin Entities / Water Supply - Water Providers***
6. If space above or below the table can be used, it might be nice to show a summary line line in TSTool fetaures, for example "132 rows, 5 selected".   I don't know if this is possible.  This can be used for quality control, such as to match the original dataset.  Adding one or more tools with icons/buttons would also put in place a design where other tools could be added.
7. More advanced features can now be considered, perhaps as separate issues, for example:  selecting rows for output or to display on the map (select on map, zoom on map, etc.), copy/paste table or parts of table (for example, filter and then copy/paste into Excel to do some calculation on numbers), saving the table to a CSV or other file, sorting the table based on clicking on column heading or other approach (see TSTool table headings or use a simpler approach).

**Comment by smalers** [comment]
Lacking metadata about the table, default column formatting depends on column type.   The column type can be determined as follows:

1. Use the original GeoJSON item type, which for primitives should be string, number, or boolean.  This assumes that the file is read into primitives of appropriate type.  Are integers read as integers or floating point numbers?  Need to know for formatting the number of digits after decimal point.
2. Determine the column type by examining data in the columns.  See the `parseFile` method in the [`DataTable`](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/Util/Table/DataTable.java) class.  This method parses the file into tokens, examines column data to determine type, and then processes the data again into final table using appropriate types.  A similar approach could be used to generically determine default column types.  A specific issue is how to handle numbers/strings that have leading zero, such as identifier for stations.  These should be treated as strings because if converted to a number the leading zero will be lost.
3. Provide a metadata file that describes the table column types.  This as a requirement would introduce more data work and additional asynchronous file handling since a second file.

For formatting floating point numbers, it is often useful to look at data units.  However, many data tables don't have units so this is difficult to implement.  I think using a default of 4 for floating point probably splits the difference and maybe auto-detect latitude and longitude and use 6 digits.

**Comment by Nightsphere** [comment]
The new push contains, in order to two messages ago:
1. Changes to the menu, so that it is displayed in the draggable gray title bar.
2. The default precision for numbers has been set to 4 for the moment. 
3. Long strings (namely URL's) will be truncated, and a clickable link will be inserted below the link in the same cell so that a new tab can be opened.
4. Extra white space to the side were caused by URL sizes, so they should be fixed now with the truncating. 
5. It seems the virtual scrolling requires each row size to be specific. When there is more data, the rows grow in size, so the scrolling obviously deals with larger sizes. Knowing this, I might be able to determine what pixel factor rows are increasing by, and so I'll try to decrease them by the same amount by default, and see if the table handles that well.
6. Still needs to be looked at
7. Still needs to be looked at

**Comment by smalers** [comment]
I updated the Poudre application to the latest InfoMapper.  The link overflow into neighboring cell is still an issue.  Look at [Water Providers](http://poudre.openwaterfoundation.org/latest/#/map/entities-water-providers).

**Comment by Nightsphere** [comment]
The main functionality of this issue has been pushed and merged, and the other ideas and issues stemming from this one have been made into their own separate issues. Closing this issue.
